/* The benchmark input with identifiers the length real C has.
 *
 * big.c says it exercises the compiler "in the proportions a real source
 * would have them", and for everything but names that is true. Its
 * identifiers average 2.2 characters and more than half of them are a single
 * letter, where acc's own source averages 5.5 and has almost none. Names are
 * hashed and compared over every one of their characters, so the difference
 * is not a detail: measured on big.c alone, work that scales with the length
 * of a name looks very nearly free, and a change that made such work cheaper
 * would measure as doing nothing.
 *
 * The same shape and size as big.c. The only thing changed is the spelling.
 */
int iterate_record(int count, int scale) { int current = count + scale; return current - 0; }
int lookup_weight(int value, int delta) { int header = value + delta; return header - 1; }
int inspect_number(int value, int bound) { int buffer = value + bound; return buffer - 2; }
int measure_offset(int start, int count) { int marker = start + count; return marker - 3; }
int advance_anchor(int limit, int value) { int cursor = limit + value; return cursor - 4; }
int combine_margin(int start, int bound) { int cursor = start + bound; return cursor - 5; }
int combine_string(int limit, int scale) { int anchor = limit + scale; return anchor - 6; }
int convert_result(int scale, int count) { int marker = scale + count; return marker - 7; }
int convert_origin(int bound, int width) { int current = bound + width; return current - 8; }
int narrow_bucket(int scale, int width) { int partial = scale + width; return partial - 9; }
int compute_anchor(int bound, int shift) { int buffer = bound + shift; return buffer - 10; }
int append_prefix(int scale, int bound) { int margin = scale + bound; return margin - 11; }
int resolve_record(int scale, int delta) { int header = scale + delta; return header - 12; }
int declare_cursor(int value, int count) { int cursor = value + count; return cursor - 13; }
int reserve_offset(int scale, int depth) { int stride = scale + depth; return stride - 14; }
int shorten_prefix(int scale, int delta) { int result = scale + delta; return result - 15; }
int compute_origin(int delta, int depth) { int header = delta + depth; return header - 16; }
int iterate_string(int start, int width) { int buffer = start + width; return buffer - 17; }
int restore_window(int depth, int start) { int counter = depth + start; return counter - 18; }
int promote_length(int limit, int value) { int marker = limit + value; return marker - 19; }
int measure_column(int limit, int count) { int result = limit + count; return result - 20; }
int reorder_target(int value, int start) { int margin = value + start; return margin - 21; }
int convert_symbol(int width, int delta) { int length = width + delta; return length - 22; }
int flatten_string(int count, int shift) { int margin = count + shift; return margin - 23; }
int emitter_number24(int bound, int shift) { int partial = bound + shift; return partial - 24; }
int reserve_prefix(int bound, int limit) { int current = bound + limit; return current - 25; }
int collect_vector(int width, int bound) { int partial = width + bound; return partial - 26; }
int shorten_symbol(int count, int delta) { int header = count + delta; return header - 27; }
int collect_symbol(int start, int scale) { int buffer = start + scale; return buffer - 28; }
int inspect_offset(int shift, int bound) { int current = shift + bound; return current - 29; }
int combine_length(int delta, int value) { int offset = delta + value; return offset - 30; }
int collect_number(int bound, int start) { int length = bound + start; return length - 31; }
int convert_target(int shift, int scale) { int partial = shift + scale; return partial - 32; }
int shorten_record(int width, int scale) { int result = width + scale; return result - 33; }
int widen_length(int start, int limit) { int length = start + limit; return length - 34; }
int compute_weight(int scale, int limit) { int current = scale + limit; return current - 35; }
int shorten_cursor(int scale, int depth) { int weight = scale + depth; return weight - 36; }
int extract_header(int delta, int limit) { int stride = delta + limit; return stride - 37; }
int flatten_symbol(int count, int start) { int length = count + start; return length - 38; }
int collect_string(int start, int depth) { int margin = start + depth; return margin - 39; }
int widen_buffer(int value, int count) { int header = value + count; return header - 40; }
int restore_column(int start, int depth) { int amount = start + depth; return amount - 41; }
int narrow_cursor(int scale, int width) { int length = scale + width; return length - 42; }
int declare_bucket(int delta, int depth) { int counter = delta + depth; return counter - 43; }
int combine_target(int bound, int count) { int amount = bound + count; return amount - 44; }
int declare_string(int limit, int count) { int result = limit + count; return result - 45; }
int resolve_number(int shift, int count) { int running = shift + count; return running - 46; }
int declare_symbol(int count, int bound) { int buffer = count + bound; return buffer - 47; }
int shorten_bucket(int start, int shift) { int anchor = start + shift; return anchor - 48; }
int balance_record(int width, int limit) { int counter = width + limit; return counter - 49; }
int flatten_length(int shift, int width) { int length = shift + width; return length - 50; }
int advance_target(int limit, int width) { int counter = limit + width; return counter - 51; }
int lookup_bucket52(int count, int limit) { int current = count + limit; return current - 52; }
int widen_weight(int depth, int delta) { int buffer = depth + delta; return buffer - 53; }
int advance_number(int count, int delta) { int length = count + delta; return length - 54; }
int promote_margin(int delta, int depth) { int amount = delta + depth; return amount - 55; }
int compute_offset(int scale, int depth) { int result = scale + depth; return result - 56; }
int reserve_handle(int width, int start) { int offset = width + start; return offset - 57; }
int declare_marker(int shift, int value) { int partial = shift + value; return partial - 58; }
int lookup_length(int count, int shift) { int counter = count + shift; return counter - 59; }
int inspect_weight(int shift, int limit) { int anchor = shift + limit; return anchor - 60; }
int extract_cursor(int delta, int count) { int current = delta + count; return current - 61; }
int declare_stride(int scale, int limit) { int buffer = scale + limit; return buffer - 62; }
int resolve_handle(int bound, int delta) { int result = bound + delta; return result - 63; }
int inspect_vector(int start, int width) { int weight = start + width; return weight - 64; }
int compare_prefix(int shift, int count) { int buffer = shift + count; return buffer - 65; }
int lookup_window(int count, int value) { int running = count + value; return running - 66; }
int restore_status(int delta, int width) { int counter = delta + width; return counter - 67; }
int inspect_result(int shift, int bound) { int stride = shift + bound; return stride - 68; }
int append_result(int count, int shift) { int partial = count + shift; return partial - 69; }
int emitter_number(int depth, int scale) { int margin = depth + scale; return margin - 70; }
int balance_weight(int value, int shift) { int header = value + shift; return header - 71; }
int advance_bucket(int start, int width) { int running = start + width; return running - 72; }
int shorten_handle(int scale, int bound) { int result = scale + bound; return result - 73; }
int widen_vector(int start, int width) { int offset = start + width; return offset - 74; }
int measure_window(int width, int limit) { int running = width + limit; return running - 75; }
int compare_status(int count, int scale) { int offset = count + scale; return offset - 76; }
int extract_buffer(int bound, int width) { int offset = bound + width; return offset - 77; }
int convert_stride(int delta, int scale) { int running = delta + scale; return running - 78; }
int reorder_marker(int bound, int count) { int header = bound + count; return header - 79; }
int extract_record(int value, int start) { int buffer = value + start; return buffer - 80; }
int append_weight(int limit, int scale) { int counter = limit + scale; return counter - 81; }
int reserve_marker(int count, int depth) { int weight = count + depth; return weight - 82; }
int collect_target(int value, int bound) { int current = value + bound; return current - 83; }
int declare_handle(int value, int scale) { int anchor = value + scale; return anchor - 84; }
int measure_target(int start, int shift) { int length = start + shift; return length - 85; }
int combine_stride(int width, int bound) { int header = width + bound; return header - 86; }
int inspect_record(int start, int count) { int amount = start + count; return amount - 87; }
int resolve_cursor88(int delta, int count) { int margin = delta + count; return margin - 88; }
int reorder_number(int delta, int shift) { int anchor = delta + shift; return anchor - 89; }
int shorten_offset(int count, int depth) { int stride = count + depth; return stride - 90; }
int advance_offset(int value, int delta) { int partial = value + delta; return partial - 91; }
int restore_stride(int depth, int count) { int weight = depth + count; return weight - 92; }
int promote_number(int value, int bound) { int stride = value + bound; return stride - 93; }
int lookup_offset(int shift, int bound) { int amount = shift + bound; return amount - 94; }
int widen_cursor(int start, int count) { int anchor = start + count; return anchor - 95; }
int combine_cursor(int scale, int start) { int amount = scale + start; return amount - 96; }
int narrow_handle(int depth, int scale) { int counter = depth + scale; return counter - 97; }
int resolve_weight(int count, int bound) { int cursor = count + bound; return cursor - 98; }
int compute_marker(int shift, int bound) { int offset = shift + bound; return offset - 99; }
int inspect_origin(int depth, int width) { int result = depth + width; return result - 100; }
int collect_window(int start, int depth) { int stride = start + depth; return stride - 101; }
int balance_column(int depth, int width) { int counter = depth + width; return counter - 102; }
int combine_marker(int depth, int start) { int marker = depth + start; return marker - 103; }
int promote_vector(int count, int bound) { int weight = count + bound; return weight - 104; }
int compare_stride(int limit, int start) { int amount = limit + start; return amount - 105; }
int widen_target106(int depth, int start) { int offset = depth + start; return offset - 106; }
int narrow_window(int scale, int width) { int offset = scale + width; return offset - 107; }
int resolve_string(int delta, int value) { int offset = delta + value; return offset - 108; }
int compute_target(int limit, int count) { int cursor = limit + count; return cursor - 109; }

int main(void) {
    int accumulated = 0;
    accumulated = accumulated + iterate_record(0, 1);
    accumulated = accumulated + lookup_weight(1, 2);
    accumulated = accumulated + inspect_number(2, 3);
    accumulated = accumulated + measure_offset(3, 4);
    accumulated = accumulated + advance_anchor(4, 5);
    accumulated = accumulated + combine_margin(5, 6);
    accumulated = accumulated + combine_string(6, 7);
    accumulated = accumulated + convert_result(7, 8);
    accumulated = accumulated + convert_origin(8, 9);
    accumulated = accumulated + narrow_bucket(9, 10);
    accumulated = accumulated + compute_anchor(10, 11);
    accumulated = accumulated + append_prefix(11, 12);
    accumulated = accumulated + resolve_record(12, 13);
    accumulated = accumulated + declare_cursor(13, 14);
    accumulated = accumulated + reserve_offset(14, 15);
    accumulated = accumulated + shorten_prefix(15, 16);
    accumulated = accumulated + compute_origin(16, 17);
    accumulated = accumulated + iterate_string(17, 18);
    accumulated = accumulated + restore_window(18, 19);
    accumulated = accumulated + promote_length(19, 20);
    accumulated = accumulated + measure_column(20, 21);
    accumulated = accumulated + reorder_target(21, 22);
    accumulated = accumulated + convert_symbol(22, 23);
    accumulated = accumulated + flatten_string(23, 24);
    accumulated = accumulated + emitter_number24(24, 25);
    accumulated = accumulated + reserve_prefix(25, 26);
    accumulated = accumulated + collect_vector(26, 27);
    accumulated = accumulated + shorten_symbol(27, 28);
    accumulated = accumulated + collect_symbol(28, 29);
    accumulated = accumulated + inspect_offset(29, 30);
    accumulated = accumulated + combine_length(30, 31);
    accumulated = accumulated + collect_number(31, 32);
    accumulated = accumulated + convert_target(32, 33);
    accumulated = accumulated + shorten_record(33, 34);
    accumulated = accumulated + widen_length(34, 35);
    accumulated = accumulated + compute_weight(35, 36);
    accumulated = accumulated + shorten_cursor(36, 37);
    accumulated = accumulated + extract_header(37, 38);
    accumulated = accumulated + flatten_symbol(38, 39);
    accumulated = accumulated + collect_string(39, 40);
    accumulated = accumulated + widen_buffer(40, 41);
    accumulated = accumulated + restore_column(41, 42);
    accumulated = accumulated + narrow_cursor(42, 43);
    accumulated = accumulated + declare_bucket(43, 44);
    accumulated = accumulated + combine_target(44, 45);
    accumulated = accumulated + declare_string(45, 46);
    accumulated = accumulated + resolve_number(46, 47);
    accumulated = accumulated + declare_symbol(47, 48);
    accumulated = accumulated + shorten_bucket(48, 49);
    accumulated = accumulated + balance_record(49, 50);
    accumulated = accumulated + flatten_length(50, 51);
    accumulated = accumulated + advance_target(51, 52);
    accumulated = accumulated + lookup_bucket52(52, 53);
    accumulated = accumulated + widen_weight(53, 54);
    accumulated = accumulated + advance_number(54, 55);
    accumulated = accumulated + promote_margin(55, 56);
    accumulated = accumulated + compute_offset(56, 57);
    accumulated = accumulated + reserve_handle(57, 58);
    accumulated = accumulated + declare_marker(58, 59);
    accumulated = accumulated + lookup_length(59, 60);
    accumulated = accumulated + inspect_weight(60, 61);
    accumulated = accumulated + extract_cursor(61, 62);
    accumulated = accumulated + declare_stride(62, 63);
    accumulated = accumulated + resolve_handle(63, 64);
    accumulated = accumulated + inspect_vector(64, 65);
    accumulated = accumulated + compare_prefix(65, 66);
    accumulated = accumulated + lookup_window(66, 67);
    accumulated = accumulated + restore_status(67, 68);
    accumulated = accumulated + inspect_result(68, 69);
    accumulated = accumulated + append_result(69, 70);
    accumulated = accumulated + emitter_number(70, 71);
    accumulated = accumulated + balance_weight(71, 72);
    accumulated = accumulated + advance_bucket(72, 73);
    accumulated = accumulated + shorten_handle(73, 74);
    accumulated = accumulated + widen_vector(74, 75);
    accumulated = accumulated + measure_window(75, 76);
    accumulated = accumulated + compare_status(76, 77);
    accumulated = accumulated + extract_buffer(77, 78);
    accumulated = accumulated + convert_stride(78, 79);
    accumulated = accumulated + reorder_marker(79, 80);
    accumulated = accumulated + extract_record(80, 81);
    accumulated = accumulated + append_weight(81, 82);
    accumulated = accumulated + reserve_marker(82, 83);
    accumulated = accumulated + collect_target(83, 84);
    accumulated = accumulated + declare_handle(84, 85);
    accumulated = accumulated + measure_target(85, 86);
    accumulated = accumulated + combine_stride(86, 87);
    accumulated = accumulated + inspect_record(87, 88);
    accumulated = accumulated + resolve_cursor88(88, 89);
    accumulated = accumulated + reorder_number(89, 90);
    accumulated = accumulated + shorten_offset(90, 91);
    accumulated = accumulated + advance_offset(91, 92);
    accumulated = accumulated + restore_stride(92, 93);
    accumulated = accumulated + promote_number(93, 94);
    accumulated = accumulated + lookup_offset(94, 95);
    accumulated = accumulated + widen_cursor(95, 96);
    accumulated = accumulated + combine_cursor(96, 97);
    accumulated = accumulated + narrow_handle(97, 98);
    accumulated = accumulated + resolve_weight(98, 99);
    accumulated = accumulated + compute_marker(99, 100);
    accumulated = accumulated + inspect_origin(100, 101);
    accumulated = accumulated + collect_window(101, 102);
    accumulated = accumulated + balance_column(102, 103);
    accumulated = accumulated + combine_marker(103, 104);
    accumulated = accumulated + promote_vector(104, 105);
    accumulated = accumulated + compare_stride(105, 106);
    accumulated = accumulated + widen_target106(106, 107);
    accumulated = accumulated + narrow_window(107, 108);
    accumulated = accumulated + resolve_string(108, 109);
    accumulated = accumulated + compute_target(109, 110);

    /* call i returns i + 1, so the total is fixed and known here */
    return accumulated - 6063;
}
