/* A skipped group whose #endif is the first line of the next window.
 *
 * acc reads a file through a window of whole lines, 4096 bytes for the
 * main file. The #endif below starts at byte 4093, so the first window
 * ends just before it -- and skip_group, finding the window's end where a
 * line should start, refilled it and read the #endif as the rest of the
 * line before, never seeing it: "#if without #endif". The filler is
 * sized to put it there; it is only text, never compiled.
 */
#if 0
skipped text, line 1: nothing here is compiled.................
skipped text, line 2: nothing here is compiled.................
skipped text, line 3: nothing here is compiled.................
skipped text, line 4: nothing here is compiled.................
skipped text, line 5: nothing here is compiled.................
skipped text, line 6: nothing here is compiled.................
skipped text, line 7: nothing here is compiled.................
skipped text, line 8: nothing here is compiled.................
skipped text, line 9: nothing here is compiled.................
skipped text, line 10: nothing here is compiled................
skipped text, line 11: nothing here is compiled................
skipped text, line 12: nothing here is compiled................
skipped text, line 13: nothing here is compiled................
skipped text, line 14: nothing here is compiled................
skipped text, line 15: nothing here is compiled................
skipped text, line 16: nothing here is compiled................
skipped text, line 17: nothing here is compiled................
skipped text, line 18: nothing here is compiled................
skipped text, line 19: nothing here is compiled................
skipped text, line 20: nothing here is compiled................
skipped text, line 21: nothing here is compiled................
skipped text, line 22: nothing here is compiled................
skipped text, line 23: nothing here is compiled................
skipped text, line 24: nothing here is compiled................
skipped text, line 25: nothing here is compiled................
skipped text, line 26: nothing here is compiled................
skipped text, line 27: nothing here is compiled................
skipped text, line 28: nothing here is compiled................
skipped text, line 29: nothing here is compiled................
skipped text, line 30: nothing here is compiled................
skipped text, line 31: nothing here is compiled................
skipped text, line 32: nothing here is compiled................
skipped text, line 33: nothing here is compiled................
skipped text, line 34: nothing here is compiled................
skipped text, line 35: nothing here is compiled................
skipped text, line 36: nothing here is compiled................
skipped text, line 37: nothing here is compiled................
skipped text, line 38: nothing here is compiled................
skipped text, line 39: nothing here is compiled................
skipped text, line 40: nothing here is compiled................
skipped text, line 41: nothing here is compiled................
skipped text, line 42: nothing here is compiled................
skipped text, line 43: nothing here is compiled................
skipped text, line 44: nothing here is compiled................
skipped text, line 45: nothing here is compiled................
skipped text, line 46: nothing here is compiled................
skipped text, line 47: nothing here is compiled................
skipped text, line 48: nothing here is compiled................
skipped text, line 49: nothing here is compiled................
skipped text, line 50: nothing here is compiled................
skipped text, line 51: nothing here is compiled................
skipped text, line 52: nothing here is compiled................
skipped text, line 53: nothing here is compiled................
skipped text, line 54: nothing here is compiled................
skipped text, line 55: nothing here is compiled................
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#endif

int main(void)
{
    return 42;
}
