#!/usr/bin/env python3
"""opt-acc's log of the calls the parser makes into the code generator.

Reads the prototypes in src/gen.h and writes src/genlog_calls.h, which
genlog.c includes three times, each with one of these defined:

  GENLOG_RENAME    `#define name genlog_name` for every call logged, which
                   gen.h includes first in the parser's files (ACC_FRONT),
                   so that their calls go through the wrappers;
  GENLOG_OPS       the enum of the calls, GL_name;
  GENLOG_WRAPPERS  each wrapper: the call written to the log, then made;
  GENLOG_REPLAY    each call made again from its record (see genlog.c).

Which calls are logged is the parser's side of gen.h: every prototype there
but those listed in NOT_LOGGED, which the parser does not make inside a
function or which are not code generation at all.

    python3 src/genlog.py src/gen.h src/genlog_calls.h
"""
import re
import sys

NOT_LOGGED = {
    'gen_init', 'inline_has', 'prescan_begin', 'prescan_param',
    'prescan_body', 'prescan_claim', 'gen_iy_can',
    'gen_finish', 'gen_nfixups', 'gen_fixup_sym',
    'gen_no_address', 'gen_nexterns', 'rt_name_all', 'gen_rt_first',
    'gen_fixup_at', 'gen_externs_helpers', 'gen_extern_at',
    'gen_extern_sym', 'gen_startup', 'gen_nlate', 'gen_late_sym',
    'gen_nbss_fixups', 'gen_bss_fixup_at', 'gen_bss_len', 'gen_bss_offset',
}

# Scalars: stored in the record as a long.
SCALAR = {'int', 'Type', 'NameRef', 'unsigned char', 'long', 'uint32_t'}


def params(text):
    text = text.strip()
    if text == 'void':
        return []
    out = []
    for p in text.split(','):
        p = ' '.join(p.split())
        m = re.match(r'(.*?)(\w+)$', p)
        ty, name = m.group(1).strip(), m.group(2)
        out.append((ty, name))
    return out


def main(src, dst):
    s = open(src).read()
    s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
    s = re.sub(r'#.*', '', s)
    fns = []
    for p in re.findall(r'^[A-Za-z][^;{}()]*\([^;{}]*\)\s*;', s, flags=re.M):
        p = ' '.join(p.split())
        m = re.match(r'(.*?)\b(\w+)\s*\((.*)\)\s*;$', p)
        ret, name, args = m.group(1).strip(), m.group(2), m.group(3)
        if name in NOT_LOGGED:
            continue
        fns.append((ret, name, params(args)))

    # Two of out.h's, which the parser calls itself: a rewind of what it
    # wrote, and a seek to write earlier in the image.
    fns.append(('void', 'out_rewind', [('int', 'here')]))
    fns.append(('void', 'out_seek', [('int', 'here')]))

    w = []
    w.append('/* Generated by src/genlog.py from src/gen.h. Do not edit. */\n')

    w.append('#ifdef GENLOG_RENAME')
    for ret, name, ps in fns:
        w.append('#define %s genlog_%s' % (name, name))
    w.append('#endif\n')

    w.append('#ifdef GENLOG_OPS')
    w.append('enum {\n    GL_RAW = 1,')
    for ret, name, ps in fns:
        w.append('    GL_%s,' % name)
    w.append('    GL_COUNT\n};')
    w.append('static const char *const gl_names[GL_COUNT] = {')
    w.append('    NULL, "(raw bytes)",')
    for ret, name, ps in fns:
        w.append('    "%s",' % name)
    w.append('};')
    w.append('#endif\n')

    w.append('#ifdef GENLOG_WRAPPERS')
    for ret, name, ps in fns:
        decl = ', '.join('%s %s' % (t, n) if not t.endswith('*') else '%s%s' % (t, n)
                         for t, n in ps) or 'void'
        w.append('%s genlog_%s(%s)\n{' % (ret, name, decl))
        w.append('    GenRec *r = gl_begin(GL_%s);' % name)
        callargs = []
        k = 0
        outs = []
        for t, n in ps:
            callargs.append(n)
            if t in SCALAR:
                w.append('    if (r) r->a[%d] = (long) %s;' % (k, n))
            elif t == 'float':
                w.append('    if (r) memcpy(&r->a[%d], &%s, sizeof %s);' % (k, n, n))
            elif t == 'GenMark *':
                w.append('    if (r) r->a[%d] = gl_mark_id(%s, GL_%s);' % (k, n, name))
            elif t == 'const char *' and name == 'gen_data':
                w.append('    if (r) r->a[%d] = gl_keep(%s, len);' % (k, n))
            elif t == 'const char *':
                w.append('    if (r) r->a[%d] = (long) (intptr_t) %s;' % (k, n))
            elif t.endswith('*'):
                # Read as well as written, maybe: what it held going in is
                # kept too, and the replay starts it from that.
                w.append('    if (r) r->a[%d] = (long) *%s;' % (k, n))
                outs.append((t, n))
            else:
                raise SystemExit('genlog.py: %s: no rule for %s' % (name, t))
            k += 1
        if len(ps) > 6 or len(outs) > 4:
            raise SystemExit('genlog.py: %s has too many arguments' % name)
        call = '%s(%s)' % (name, ', '.join(callargs))
        if ret == 'void':
            w.append('    %s;' % call)
            ret_store = None
        else:
            w.append('    %s ret = %s;' % (ret, call))
        for i, (t, n) in enumerate(outs):
            w.append('    if (r) r->out[%d] = (long) *%s;' % (i, n))
        if ret != 'void':
            if ret.endswith('*'):
                w.append('    if (r) r->ret = 0;')
            else:
                w.append('    if (r) r->ret = (long) ret;')
        w.append('    gl_end(r);')
        if ret != 'void':
            w.append('\n    return ret;')
        w.append('}\n')
    w.append('#endif\n')

    w.append('#ifdef GENLOG_REPLAY')
    for ret, name, ps in fns:
        w.append('case GL_%s: {' % name)
        callargs = []
        k = 0
        outs = []
        for t, n in ps:
            if t in SCALAR:
                callargs.append('(%s) r->a[%d]' % (t, k))
            elif t == 'float':
                w.append('    float %s;\n\n    memcpy(&%s, &r->a[%d], sizeof %s);' % (n, n, k, n))
                callargs.append(n)
            elif t == 'GenMark *':
                callargs.append('gl_replay_mark(r->a[%d])' % k)
            elif t == 'const char *' and name == 'gen_data':
                callargs.append('gl_kept(r->a[%d])' % k)
            elif t == 'const char *':
                callargs.append('(const char *) (intptr_t) r->a[%d]' % k)
            elif t.endswith('*'):
                base = t[:-1].strip()
                w.append('    %s o%d = (%s) r->a[%d];' % (base, len(outs), base, k))
                callargs.append('&o%d' % len(outs))
                outs.append((base, n))
            k += 1
        call = '%s(%s)' % (name, ', '.join(callargs))
        if ret == 'void':
            w.append('    %s;' % call)
        elif ret.endswith('*'):
            w.append('    (void) %s;' % call)
        else:
            w.append('    gl_check_ret(r, (long) %s);' % call)
        for i, (t, n) in enumerate(outs):
            w.append('    gl_check_out(r, %d, (long) o%d);' % (i, i))
        w.append('    break;\n}')
    w.append('#endif')

    open(dst, 'w').write('\n'.join(w) + '\n')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
